### ISSUE TITLE
One plan, two subscriptions

### ISSUE THREAD

**Issue by evmimagina** [charleszipp/azure-pipelines-tasks-terraform#114]
Hi,

Quick question, would it be possible to specify a backend in one subscription and provision the infrastructure to another one? Any indications about how to proceed?

Many thanks,

**Comment by charleszipp** [comment]
Hey @evmimagina, I do not have a recommendation for how you could utilize the task to support this configuration. You could create the backend ahead of time outside the task. However, I believe when init runs, it will assume the backend exists in the same subscription as the service connection. 

Could you provide a bit more detail on your use case? For example, do you need this configuration because a different team in your org owns and manages the backend storage than the dev/engineering teams? Any detail you can provide would help ensure that what is added to support this fits your case.

**Comment by evmimagina** [comment]
Hi,

Problem solved, the only requirement for the stages beyond the init one, wich should point to the same subscription where the backend config lives, is to include on tf scripts the storage account key for the backend configured storage account;

terraform {
backend "azurerm" {
    access_key           = "__storageaccountkey__"
  }
}

Collecting the storage account key could be done during previous steps.

Thanks for looking into this, I close the request.

Regards,

**Comment by charleszipp** [comment]
Thanks for providing the update and guidance for others that might have similar issue @evmimagina
