### ISSUE TITLE
Allow use of modules contained within private git-style Azure Repos

### ISSUE THREAD

**Issue by gabrielmccoll** [charleszipp/azure-pipelines-tasks-terraform#165]
Terraform 0.13.4 installed as first step.
I have my terraform modules in Repo B which is another Azure Repo.
Repo A has .tf consuming modules form Repo  B
Terraform init task tries to git clone in Repo A from module B and fails. 
I can use a bash script before it, to set the config. 
If I put Terraform init in that script, it works, clones down the modules and inits fine. 

If I remove the "terraform init" part from bash below and replace it with your Terraform Init task so I can pull in the Azure Backend and using the Service Connection , it fails with authorization issues. (same error I get before I do the git config below)
I've tried it at system level too and still doesn't work to carry across.

```
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            git config --global credential.helper '!f() { printf "%s\n" "username=$SYSTEM_ACCESSTOKEN" "password=$SYSTEM_ACCESSTOKEN"; };f'
            cd $(TerraformWorkingDirectory)
            terraform init 
        env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```

**Comment by favoretti** [comment]
Outside of the fact that this a peculiar thing, you know you can reference modules are git refs in terraform itself?
Or are you saying that repo A and repo B require different set of credentials to clone?

**Comment by gabrielmccoll** [comment]
> Outside of the fact that this a peculiar thing, you know you can reference modules as git refs in terraform itself?
> 
> Or are you saying that repo A and repo B require different set of credentials to clone?

Yes, that's what in doing. 
So source is git::http:// and so on

They require different creds kind of. 

It should have permission when I terraform init but doesn't because the git cred manager doesn't have the creds in it. 

So I add a bash task to add those creds in from the build agent. 

If I terraform init in the same bash task. No problem. It clones. 

If I use the terraform init task , it doesn't use the git cred manager creds I put in in the bash step and so access denied. 

Right now am working around by doing two inits. 

One in bash with backend=false to download the modules in RepoB

The the terraform task init that sets up the backend using the service connection.

**Comment by favoretti** [comment]
Hmm, tricky. Nothing from this https://www.terraform.io/docs/internals/credentials-helpers.html helps?

**Comment by gabrielmccoll** [comment]
not sure,  terraform itself seems to be finding the git creds ok if I use terraform commandline from a bash script in the same pipeline.
If I use your task though, it ignores the gitconfig I setup in previous step.

**Comment by charleszipp** [comment]
This probably has something to do with how the underlying library for azure pipeline extensions works. There is a tool runner object that is responsible for executing binaries like terraform, azure cli, etc. However, I believe, it spawns the execution into a child process. This sometimes has a side effect of not carrying everything from the root process such as credentials or otherwise. It should however, carry everything in process.env by default.

That would explain why when you run in a single bash script it works but, when you get the credentials ahead of the terraform task it doesnt. In the latter the terraform part is run in a child process. 

@gabrielmccoll basically what I believe is needed is the ability to support leveraging modules from an Azure Repo. Typically you would handle this by setting the git config ahead of the terraform commands. I think to solve this we will need to find a way to provide these credentials to terraform or git in the form of env vars that will be used by the child process. Thoughts @favoretti @gabrielmccoll ?

**Comment by gabrielmccoll** [comment]
That could work yes!It sounds like what I'm seeing but I won't claim to be anything close to an expert. 
The way I deal without it at present is to pass the agent.systemtoken in as env variables and use that in the git config as both user name and password. 
That's ideal because it means I just need to give the build agent for this project, permission to the project I want to pull modules on and don't have to pass other creds or add secret variables. 
But if could do that and have options to pass different creds that would work too?

**Comment by charleszipp** [comment]
I like the token based approach as it relies on just RBAC and existing env's rather than storing secrets. However, I could see the secrets being necessary if the module exists in a different Azure DevOps org/tenant. 
If my understanding is correct, the modules being targeted are within the same tenant and org (possibly even same project) since you are able to grant permission and use a token. Is that correct @gabrielmccoll ?
The username/password I think would only be needed if the modules are in a private repo within a different tenant and possibly org.

**Comment by gabrielmccoll** [comment]
Yep the modules live in a separate Project in the same Org in my case. 
So I give project A build account permission to project B git repos. 
Hence the need for Auth needing to be put together using the agent token. 

Now if it was a separate org I'd need to pass in an API key or something using the git config but I haven't had to do that yet.

**Comment by favoretti** [comment]
I just thought about a possible workaround in the meantime. If you use ssh-based auth, you can put the same public key to both repos. Or am I saying something stupid now?

**Comment by gabrielmccoll** [comment]
> I just thought about a possible workaround in the meantime. If you use ssh-based auth, you can put the same public key to both repos. Or am I saying something stupid now?

Eh it's not stupid but really I don't want to be adding new creds to each individual repo , whether that's adding variables or an ssh key. 
Right now I can just give permissions to the build agent and it works for every repo in the same project

**Comment by scott-doyland-burrows** [comment]
I have my terraform modules in a different Azure DevOps Collection/Project (on-prem Azure DevOps) to my root module.  My pipelines run from the Collection/Project that the root modules resides in.

I defined an ssh key to my Azure DevOps account (would be better to use an account specifically setup for Terraform rather than an persons account).

I checked I could clone via ssh to my local machine - just to ensure the ssh key worked.

Then in my pipeline I used the "Install ssh key" task to just insert the private ssh key as the first task.

Terraform init then can clone down the modules from the "remote" repo using that private ssh key.

**Comment by favoretti** [comment]
Thank you Scott. That’s exactly what we do as well and what I meant, you
worded it perfectly.

**Comment by charleszipp** [comment]
Deprioritizing this as there seems to be a reasonable way to accomplish the authentication via ssh as @scott-doyland-burrows and @favoretti indicated. If there is additional information and interest on simplifying this, the prioritization can be revisited in the future.

**Comment by FernandoMiguel** [comment]
I fixed this 

```
  - task: AzureCLI@2
    displayName: configure git auth
    inputs:
      azureSubscription: ${{ parameters.AZURERMCONNECTION }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: git config --global url."https://<<MY_ORG_HERE>>:$(System.AccessToken)@dev.azure.com".insteadOf https://dev.azure.com
      addSpnToEnvironment: false
```

it makes use of git insteadOf to add the token
