### ISSUE TITLE
Azure DevOps on-prem server still stuck at version 0.6.7

### ISSUE THREAD

**Issue by scott-doyland-burrows** [charleszipp/azure-pipelines-tasks-terraform#219]
I am unsure if this is an issue with our on-prem Azure DevOps server or some odd issue with the Terraform extension.

Our Azure DevOps server is still at 0.6.7 of the extension.

I went into the ```Extensions``` page on the Azure DevOps site,
clicked on the ```Terraform``` extension and then
```Marketplace``` and then on ```Manage```

I then see a green tick next to 0.6.7 and a red cross next to 0.6.8 and it says error.  I click on ```error``` and it opens an error windows on the page which says:

```
Task definition input 'command' and Task definition input 'runAzLogin' must belong to same group as they are dependent inputs for Task with ID '<a long UID>'.
```

Any ideas what this may mean - seems related to when 0.6.7/8 had the update to run the ```az login```

Thanks.

**Comment by charleszipp** [comment]
I had a quick look at the task.json for the cli tool. The `runAzLogin` input has a groupName defined while `command` does not. I suspect since runAzLogin also defines a visibility rule based on what command is selected (this is for classic ui not yaml) ADO expects them to be in the same group or, both be absent from a group.

This must be unique to ADO Server as the hosted one does not report this error
![image](https://user-images.githubusercontent.com/4292559/107393504-80142100-6ac0-11eb-9e69-12f14b00429a.png)

However, I think this is a simple one line fix. There is no reason the `runAzLogin` needs to be assigned to a particular group. So likely we just need to drop the groupName in the task.json and this will resolve.

**Comment by charleszipp** [comment]
@scott-doyland-burrows keep an eye out for 0.6.9 to be released in the next couple days. Feel free to reopen the issue if the message occurs with 0.6.9
