### ISSUE TITLE
Debugging 

### ISSUE THREAD

**Issue by MaxMelcher** [charleszipp/azure-pipelines-tasks-terraform#23]
I just forked this awesome task to give #3 a try - but I struggle to debug the 'plan' command. 
I read the readme several times, but I cant get it to work:

```
Terraform v0.11.9

Your version of Terraform is out of date! The latest version
is 0.11.11. You can update by downloading from www.terraform.io/downloads.html
##vso[task.debug]Exit code 0 received from tool 'C:\ProgramData\chocolatey\bin\terraform.exe'
##vso[task.debug]STDIO streams have closed for tool 'C:\ProgramData\chocolatey\bin\terraform.exe'
##vso[task.debug]command=plan
##vso[task.debug]System.TeamFoundationCollectionUri=undefined
##vso[task.debug]task result: Failed
##vso[task.issue type=error;]Error: Endpoint auth data not present: SYSTEMVSSCONNECTION
##vso[task.complete result=Failed;]Error: Endpoint auth data not present: SYSTEMVSSCONNECTION
```

I did setup the .env file and the init command works fine. 
Additionally I logged in via **tgx login**

What do I miss?

Thanks for pointers,
Max

**Comment by charleszipp** [comment]
@MaxMelcher Thanks for giving #3 a try!

When i added the secure files feature, there were a few additional environment variables that were needed that I forgot to add to the .env-sample. I will get a PR opened to add these so future potential contributors dont hit the same problem.

These settings are needed to access secure files that are uploaded to Pipelines > Library > Secure Files. The connection handshake is currently happening when the task starts. This means these settings currently have to be in place when running locally even if you did not specify a secure file

Until then, add these to your .env file
```
# The azure devops url to your target or (i.e. https://dev.azure.com/chzipp)
SYSTEM_TEAMFOUNDATIONCOLLECTIONURI=my-azure-devops-org-url
# The name of the project within the org provided above
SYSTEM_TEAMPROJECT=my-azure-devops-org-project
# Personal Access Token for authentication
ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN=my-personal-access-token
```
Lastly, for running locally, since the support for the original var file has been removed, I would use the command options input instead.
```
# Remove/Comment this line
INPUT_VARSFILE=default.vars
# Replace it with 
INPUT_COMMANDOPTIONS='-var-file default.vars'
```

Let me know if this gets you around the issue you had

**Comment by MaxMelcher** [comment]
thanks, worked like a charm!
