### ISSUE TITLE
From latest version 0.6.20 - error:- Error retrieving keys for Storage Account

### ISSUE THREAD

**Issue by thomast1906** [charleszipp/azure-pipelines-tasks-terraform#278]
**Describe the bug**
From the latest version 0.6.20 - our pipelines are failing with errors

```
Initializing modules...
- staticwebsite in ../../modules/staticwebsite

Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: Failed to get existing workspaces: Error retrieving keys for Storage Account "tamops12345": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'tamops12345' could not be found."

##[error]Terraform command 'init' failed with exit code '1'.:  Failed to get existing workspaces: Error retrieving keys for Storage Account "tamops12345": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'tamops12345' could not be found."
##[error]

Error: Failed to get existing workspaces: Error retrieving keys for Storage Account "tamops12345": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'tamops12345' could not be found."
```

To note:- The service principal (backendServiceArm) is configured initially on a separate subscription to where the storage account is located, previous versions we added this to our Terraform provider

```
terraform {
  required_version = ">= 0.13.0"

  backend "azurerm" {
    subscription_id  = "xxxx-xxxx-xxxx-xxxxx"
  }
```

**To Reproduce**
1. Example task that was working in previous versions

```
      - task: TerraformCLI@0
        displayName: terraform init
        inputs:
          command: init
          workingDirectory: '$(System.DefaultWorkingDirectory)/components/${{ parameters.component }}'
          backendType: azurerm
          backendServiceArm: '${{ parameters.service_connection }}'
          backendAzureRmResourceGroupName: 'tamops12345'
          backendAzureRmStorageAccountName: 'tamops12345'
          backendAzureRmContainerName: '${{ parameters.backendAzureRmContainerName }}'
          backendAzureRmKey: '${{ parameters.component }}.tfstate'  

```

provider.tf

```
terraform {
  required_version = ">= 0.13.0"

  backend "azurerm" {
    subscription_id  = "xxxx-xxxx-xxxx-xxxxx"
  }
```

**Expected behavior**
Terraform to init correctly as previous versions of this task.

Current behaviour is mentioned in Describe the Bug

**Current fix/workaround**

Added `commandOptions` with `'-backend-config=subscription_id=xxxx-xxxx-xxxx-xxxxx' ` to my task, to allow terraform init to work correctly with correct storage account & subscription

```
      - task: TerraformCLI@0
        displayName: terraform init
        inputs:
          command: init
          workingDirectory: '$(System.DefaultWorkingDirectory)/components/${{ parameters.component }}'
          backendType: azurerm
          backendServiceArm: '${{ parameters.service_connection }}'
          backendAzureRmResourceGroupName: 'tamops12345'
          backendAzureRmStorageAccountName: 'tamops12345'
          backendAzureRmContainerName: '${{ parameters.backendAzureRmContainerName }}'
          backendAzureRmKey: '${{ parameters.component }}.tfstate'  
          commandOptions: '-backend-config=subscription_id=xxxx-xxxx-xxxx-xxxxx' 
```

**My ask**

Is it a bug or known that this issue we found has been introduced in  0.6.20 & going forward? Hopefully this issue assists with others who may be facing same issue if so.

**Comment by charleszipp** [comment]
Hi @thomast1906, I believe that setting `subscription_id` in the template worked in previous versions because the task was still using the old configuration variables that have the `arm_` prefix before 0.6.20 (i.e. `arm_subscription_id`. The use of `subscription_id` probably took precedence over the old/deprecated `arm_subscription_id` variable.

With the release of terraform 0.15, terraform stopped supporting the `arm_` prefixed configuration and using these would cause terraform to fail. This task was forced to switch over to the new supported configuration to get users pipelines running again. After that switch, the backend-config is now using `subscription_id` which probably rendered your original approach no longer usable.

There are currently no plans to adjust the task to accommodate this scenario since 0.15 requires use of `subscription_id`. Furthermore, terraform exe itself would be responsible for whether subscription in the template or on the command line takes precedence. With that said, I would suggest two things. First, the approach you are using is valid. You could also use self-configured option which will prevent the task from supplying any backend-config options. Others that use self-configured option store their SPN creds in a ADO secure file which is encrypted and not readable by human after upload. Second, there is an open issue to allow backend to exist on a different subscription than what is targeted by the provider/deployment (#257). I would suggest having a look at that issue and see if it maps to your case. If so, thumbs up the opening post or comment.

**Comment by thomast1906** [comment]
Cheers @charleszipp - we are happy with the commandOptions mentioned above
