### ISSUE TITLE
SecureVarFile with PartialConfiguration

### ISSUE THREAD

**Issue by kalalvishal** [charleszipp/azure-pipelines-tasks-terraform#303]
Hello,

I am trying to use secureVarsFile with AzureRMBackend partial configuration, however the configuration is unable to leverage the securevarfile for some reason. Here is the var file details I am providing:

INPUT_WORKINGDIRECTORY="./AVDDemo/"
backendType="azurerm"
ensureBackend=true
backendServiceArm="ServiceConnectionName"
backendAzureRmSubscriptionId="0000-0000-0000-0000-0000-0000"
backendAzureRmResourceGroupName="RG-TFState"
backendAzureRmResourceGroupLocation="EastUS"
backendAzureRmStorageAccountName="strgact1234567899"
backendAzureRmContainerName="tfstate"
backendAzureRmKey="tfstate.tfstate"
allowTelemetryCollection=false
backendServiceArmAuthorizationScheme="ServicePrincipal"
backendServiceArmSubscriptionId="0000-0000-0000-0000-0000-0000"
 
I also tried to populate the details completely in example file given [here ](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/tree/main/tasks/terraform-cli#create-environment-file) with and without TF_VAR but no luck. I am sure the details are correct as If I give within the yaml templates, works fine.

Any suggestions will be highly appreciated.

**Comment by jason-johnson** [comment]
So you run the terraform locally and it doesn't work but if you run it in a pipeline it does?

**Comment by kalalvishal** [comment]
Hi @jason-johnson, if I use securefile in the pipelines it won't work but works fine if I pass the same values as inputs of task.

**Comment by jason-johnson** [comment]
Could you run a task (e.g. `find` if on linux) to print out the files in the terraform directory?  Just to make sure the secure file is ending up where you expect it to.

**Comment by jason-johnson** [comment]
Or, are you using the secureVarsFile variable like:

```
task: TerraformCLI@0
displayName: 'terraform plan'
inputs:
command: plan
workingDirectory: '$(System.DefaultWorkingDirectory)'
environmentServiceName: '***'
secureVarsFile: 'myFile'
```
?

**Comment by kalalvishal** [comment]
@jason-johnson I am passing it like:
        - task: TerraformCLI@0
           displayName: Terraform Init
           inputs:
             command: 'init'
             workingDirectory: '$(System.DefaultWorkingDirectory)'
             secureVarsFile: 'secure.env'

**Comment by kalalvishal** [comment]
> Could you run a task (e.g. `find` if on linux) to print out the files in the terraform directory? Just to make sure the secure file is ending up where you expect it to.

yes, I tried to run ls and I can see the file. Also, in the pipeline run log with debug I see the the file details: **##[debug]secure file name for id 344f26dc-ccde-4f91-b627-XXXXXXXXXXXXX= secure.env**

**Comment by jason-johnson** [comment]
That's bizarre, we have [this](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/blob/main/pipelines/test/init_with_self_configured_backend.yml) test which uses secureVarsFile and it's working.  I know because when I took over this task I didn't update this file so this test failed until I updated it.

**Comment by jason-johnson** [comment]
Oh sorry, that's using another task to download the secure file first.  [This one](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/blob/main/pipelines/test/local_exec_az_cli.yml) is using `secureVarsFile `in the `terraformCli ` task and that is also working.  I note it is using the GUID instead of the name though.

**Comment by kalalvishal** [comment]
@jason-johnson I copied the securefile with CopyFiles@2 to the terraform directory. Also if I do cat, i can see the content of the file. In the example you gave, any reason of not using securefile for init? also, what details are you passing in the securefile?

**Comment by jason-johnson** [comment]
The first example did not use the secureVarsFile field and I'm not sure why.  The second example does use it and that one is also passing the test just fine.  I know the file is being used because when I took over this project I didn't have the file and the task was failing until I made one with the correct values.  It just has backend variables.

**Comment by jason-johnson** [comment]
Hi @kalalvishal, were you able to resolve this?

**Comment by jason-johnson** [comment]
No further updates received.  Closing.  Feel free to open if there is any additional information.
