### ISSUE TITLE
I just enabled azure container and blob versions. Do we have to explicitly state to use the latest container/blob version or is 'latest' default?

### ISSUE THREAD

**Issue by jsngee** [charleszipp/azure-pipelines-tasks-terraform#420]
Using terraformcli@0 at the moment. Do you recommend upgrading to terraformcli@1 and why?

I just enabled azure container and blob versions. Do we have to explicitly state to use the latest container/blob version or is 'latest' default?

Is there a way I can specify a container ID or blob ID as a parameter as well? In case I need to deploy a specific version in the future. Thank you.

**Comment by jason-johnson** [comment]
Hi.  Sorry if the documentation doesn’t make this clear enough . `@0` is for the most recent release with a `0.*` tag, `@1` is the latest `1.*`.  Since there is no `2.*` release, `@2` is always the most recent (tagged or untagged) commit to main (any accepted PR). So generally you would want `@1`. `@2` would be when you are waiting on a fix and don’t mind potential instability to help test or can’t wait for a formal release. 

For your other questions, is this for when the extension creates the blob for the state file? I’m not really sure which one this takes, I would assume it takes the latest (I believe it’s using az CLI for this) but this functionality is really just to make testing easier. Normally the container would be created outside of the job that is using it in production systems

**Comment by jason-johnson** [comment]
Hi @jasong1978, did my response address your question?

**Comment by jason-johnson** [comment]
No response from requester and this does not appear to be a bug.  Closing for now, please let me know if something more is needed here.
