### ISSUE TITLE
Run azure cli login as provided service principal to allow local-exec provisioner to run azure cli commands

### ISSUE THREAD

**Issue by jrutila** [charleszipp/azure-pipelines-tasks-terraform#50]
I am using 'local_exec' in my terraform files. Like this

```
resource "azurerm_storage_account" "sa-main" {
        name                    = "ngh${var.deployment}maina"
        resource_group_name     = "${azurerm_resource_group.rg.name}"
        location                = "${azurerm_resource_group.rg.location}"
        account_kind            = "StorageV2"
        account_tier            = "Standard"
        account_replication_type= "LRS"

        provisioner "local-exec" {
                command = "az storage blob service-properties update --account-name ${azurerm_storage_account.sa-main.name} --static-website
--index-document index.html --404-document index.html"
        }
```

If I have "terraform init" *with* "Create backend" option on, it will call az login on init:
```
[command]/usr/bin/az login --service-principal -t *** -u *** -p ***
```

If it is not checked, it will skip the az login and my local-exec will not work.
```
 azurerm_storage_account.sa-main: Error running command 'az storage blob service-properties update --account-name nghstagemaina --static-website  --index-document index.html --404-document index.html': exit status 1. Output: ERROR: Please run 'az login' to setup account.
```

Would it be possible to run the az login always on init or int apply? Code is there already, it just needs to be run.

**Comment by charleszipp** [comment]
@jrutila  
Thanks for taking the time to provide this feedback. I believe this should be possible but, I have a couple questions first.

1. Can you clarify during which command does the error actually occur (i.e. init or apply)?
2. Can you confirm the local-exec works if you check the "Create backend" flag during init?
3. If you said no to question 2, are you running init and command you provided in question 1 on the same build agent? (i.e. make sure they are not split across different agent jobs)

**Comment by jrutila** [comment]
1. It fails on apply
2. local-exec works if I check "Create backend" flag during init (tried to say that in original issue)
3. They are running on the same agent (hence, it is working with create backend)

On a side-note I think the azurerm backend does not write any blob to the blob storage but I will open a new issue if I don't find any help from the net.

**Comment by charleszipp** [comment]
Thanks for the quick answers @jrutila 

This task's scope by design only creates the resource group, storage account, and container. Terraform itself should create the actual blob file within the container. 

One thing to note, that as of the change that was made to accomodate #42, the task will not perform any modifications on the storage account if it already exists. This would include skipping the container creation. Did you statement "does not write any blob" mean that the container is not being created? If not, I would suggest going ahead and opening a new issue.

**Comment by jrutila** [comment]
The container is created so init definitely works right in that sense. It is indeed different issue (in terraform, not this project necessarily) that terraform does not write the state to azure. I m investigating it on local cli at the moment.

**Comment by jrutila** [comment]
The blob wasn't created because I didn't have the azurerm backend configuration in my tf-file so it had nothing to do with this plugin.

**Comment by sanderobdeijn** [comment]
@jrutila  how did you configure the backend to correctly call the az login? 
I have the same issue

**Comment by evertonmc** [comment]
@charleszipp I still have issues here when I try to run CLI commands in local-exec and have a storage backend. How can I still run cli which requires `az login`?

**Comment by favoretti** [comment]
@evertonmc You could supply it with secureFile with .env extension that sets ARM_SECRET_KEY environment variable for now.

**Comment by charleszipp** [comment]
Adding notes from another project related to this issue...

Provisioner was required that executed az cli commands. This mean that az login needed to be execute in order for apply to be able to successfully run the provisioner. Because apply does not currently run az login, the provisioner failed. Therefore, this extension was not able to be used for the apply step. Instead custom powershell was used to execute terraform apply as a workaround.

If the extension executed az login prior to apply, this would have allowed the extension to be used for the apply step.
