### ISSUE TITLE
Use Service Connection principal for terraform plan/apply/destroy

### ISSUE THREAD

**Issue by Zenocolo** [charleszipp/azure-pipelines-tasks-terraform#52]
First of all, thank you for developing this plugin, love it! An issue I came recently around is that when I use AzureRM backend (created during terraform init command) for terraform plan/apply/destroy, I will have to provide my Service Principal via Service Connection (Environment Azure Subscription) AND Service Principal via vars file. In my view this is wrong, plan/apply/destroy should be possible by using "Environment Azure Subscription" only.  Unfortunately when I do not define SPN's via vars file as well, my tasks runs into timeout after it aquired a lock on my blob storage. Are you aware of this issue or do I do something wrong?

**Comment by charleszipp** [comment]
Hey @Zenocolo, you should not have to do this. I have seen a similar issue if the blob has a lock taken out prior to running your terraform command. This could happen if the blob file was opened for edit from the azure portal. Can you send me the output with the error when you do not provide the spn's as var input? Also, can you provide the terraform templates you are trying to run? If you want, you can email these to me so they are not publicly posted here.

**Comment by charleszipp** [comment]
Hey @Zenocolo 

Thanks for sending the templates. I noticed that you have the SPN creds defined as variables within your templates. This would explain to me why you need to provide these as part of the var-file (or var args). If you do not provide these, what used to happen is the agent would freeze because its waiting for you to input them to the terminal manually (as it does if you run it without provided from a command prompt locally). However, you have no way to input those values so everything freezes.

I believe I have an issue open to attach input=false on the end of the command args to make sure terraform throws error exit code so the build/release pipeline fails under this condition rather than freezing.

Here is what i would suggest in your templates to try before i dig in deeper to this..
First, do not provide any of the properties for the backend definition. These are provided at runtime via env vars so you dont need them. Change your backend to this...
```
terraform {
  backend "azurerm" {
  }
}
```
Second, under your provider definition, do not provide any properties. Again, these are provided at runtime via env vars. If you want to provide the version, thats fine (i usually do).
```
provider "azurerm" {
}
```
Third, remove the variables for the SPN creds, sub, and tenant. You can retrieve these at runtime from a data provider
Fourth, in the templates where you are referencing the client_id, tenant, and/or subscription, add this [data provider](https://www.terraform.io/docs/providers/azurerm/d/client_config.html). You can then access the object_id, tenant, and sub of the SPN running the task (which should be your spn)
```
data "azurerm_client_config" "current" {}
resource "azurerm_key_vault" "kv_core" {
  tenant_id                   = "${data.azurerm_client_config.current.tenant_id}"
```

After you make these changes, you should no longer need to provide your SPN's as they are not defined as variables in the templates. You will instead be able to retrieve them at runtime via the client_config data provider. 

I would suggest you ensure this works locally with an SPN before you try to test it in the ADO pipeline. You can do this by running the terraform commands with ARM_* env variables set. You can have a look at how i do this in vs code by looking at the .vscode/task.json from this [pr](https://github.com/microsoft/code-with-engineering-playbook/pull/38)

**Comment by Zenocolo** [comment]
Hi Charles, thanks a lot for coming back, you were right, with your fixes my pipeline worked flawlessly, we can close this issue.

**Comment by charleszipp** [comment]
Thanks for updating @Zenocolo. Glad that information helped resolve the issue!
