### ISSUE TITLE
Using -var inline is not supported

### ISSUE THREAD

**Issue by SamirFarhat** [charleszipp/azure-pipelines-tasks-terraform#57]
Used Extension : Terraform Build & Release Tasks Charles Zipp 
Problem:
We cannot use the -var to set variables inline during plan and apply, this is because by default the input=false is added to the command. Why this limitation ??

**Comment by charleszipp** [comment]
@SamirFarhat 

The input option controls whether or not the command line prompts users to input variables that were not provided with the initial apply/plan command. It does not cause it to ignore -var arguments. 
![image](https://user-images.githubusercontent.com/4292559/58337251-01b6ad80-7e0b-11e9-9194-e449c86b7ea8.png)
https://www.terraform.io/docs/commands/apply.html

This input=false setting was deliberate to prevent builds/releases from running indefinitely. If terraform asked for a var input during the context of a build/release, the user would not be able to provide such input. Thereofore the build would be hung indefinitely.

Can you please post your task setup and any errors you may be getting when running your pipeline? I suspect the issue you are having has a different root cause.
